# Generated by Django 4.2.2 on 2023-07-07 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('price', models.PositiveIntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='mobi_market/card_items/')),
                ('short_description', models.CharField(max_length=150)),
                ('detailed_description', models.TextField()),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_card_products', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Card item',
                'verbose_name_plural': 'Card items',
            },
        ),
    ]
